### ISSUE TITLE
dev: New button and drawer styles

### ISSUE THREAD

**Issue by TimberKito** [Elijah-0616/bdLite#8]
#7 
* 优化了搜索按钮
* 新增设置抽屉页
* 实现动态背景的启动与暂停

@Elijah-0616 
搜索按钮样式未设置
设置按钮样式未设置
抽屉栏样式为未置

**Comment by Elijah-0616** [comment]
@TimberKito 按钮和抽屉已设置样式

**Comment by TimberKito** [comment]
#9   抽屉新增卡片样式，需要对其样式进行设置
![I0U`}5(HN()CYK%GMX23 Y7](https://user-images.githubusercontent.com/57060551/149674066-a4a3f982-fd71-487f-adc3-95eac39b1417.png)

**Comment by Elijah-0616** [comment]
样式已处理，且已添加动画 @TimberKito
